export const state = {
  deck: [],
  players: [],
  discards: [[], [], [], []],
  currentTurn: 0,
  turnPhase: "draw",
  selectedTile: null,
  riichiChecked: false,
  riichiActive: false,
  roundStarted: false,
  roundResult: null,
  actionLog: [],
  lastDrawnTile: null,
  melds: [],
  pendingCall: null,
};
